 @startuml
component "Lokalise A" as locA
component "Lokalise B" as locB
package "container A" {
    component "UI A" as uiA
}
package "container B" {
    component "UI B" as uiB
}
component "Service A" as svcA
component "Service B" as svcB
component "Product A" as prodA
component "Product B" as prodB

uiA -u-> prodA
locA -u-> uiA
locB -u-> uiB
' Used to align graphics
locA -[hidden]r- locB
svcA -u-> prodA
uiB -u-> prodB
svcB -u-> prodB

svcA -[hidden]u-> prodB
uiA -[hidden]u-> prodB

@enduml