 @startuml

participant "Lightning App" as ligapp
participant "Lightning Gateway" as gateway
participant "Design Order" as design
queue "Event Queue \n(Fallback)" as events
database "Repository" as dorepo
entity "Entity" as doent
participant "Collaboration" as collab
participant "Order" as order

== Initialization ==
design -> design : RunEventPubSub
== Design Order Create ==
ligapp -> gateway : CreateDesignOrder
gateway -> design : CreateDesignOrder
design -> design : createDesignOrder
design -> events : publishToPubSub
design -> dorepo : CreateDesignOrder
dorepo -> doent : addAction(CreateShare)
dorepo -> doent : addAction(CreateOrder)
dorepo -> doent : addAction(OrderUpdateNotify)
dorepo -> doent : addAction(OrderUpdateEmailGP)
dorepo -> doent : addAction(OrderUpdateNotificationGP)
dorepo -> doent : addAction(OrderUpdateEmailLab)
dorepo -> doent : addAction(OrderUpdateNotificationLab)
dorepo -> doent : createRequestMetaBlob
dorepo -> dorepo : createEvent
design --> dorepo : ProcessAndUpdateEvents
dorepo -> dorepo : getByDesignOrder
dorepo -> design : processEvents

group forloop ACTIONS
    design -> design : createShare
    activate design
    design -> collab : CreateShare
    deactivate design
    design -> design : createOrder
    activate design
    design -> order :  CreateOrder
    deactivate design
end


@enduml