@startuml

participant "Lightning App" as ligapp
participant "Lightning Gateway" as gateway
participant "SureSmile Order" as ssmile
participant "ccproc" as ccproc
database "Repository" as dorepo
entity "Entity" as doent

== Initialization ==
ssmile -> ccproc : Create
ccproc -> ccproc : 
== SureSmile Order Create ==
ligapp -> gateway : CreateSureSmileOrder
gateway -> ssmile : CreateOrder
ssmile -> ssmile : createOrder
ssmile -> ssmile : createSureSmileCreateOrderRequest
activate ssmile
ssmile -> ccproc : AddActionSingleton(actionCreateOrder)
ssmile -> doent : parseDentalExam
ssmile -> ssmile : getPatientDetails
ssmile -> doent : gatherDocuments
ssmile -> ssmile : getSignedURLs
deactivate ssmile
ssmile -> ccproc : ProcessFastlane

@enduml